import type { FeedEntry } from "@/lib/types";

export const DEMO_GAME_ID = "demo-den-kc-mnf";

export const DEMO_BANNER =
  "DEMO — KC 31 DEN 10 · MNF Arrowhead · not live · ESPN recap gameId 401872931 · X crawl metrics cited in digest only";

export const denKcMnfDemoEntries: FeedEntry[] = [
  {
    id: "demo-den-kc-mahomes-legs",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Mahomes rush TD opener — KC lead",
    body: "Opening drive: Mahomes rushing TD (“legs” energy). Chiefs score first at Arrowhead MNF.",
    postedAtLabel: "Q1 opener",
    path: "public-live",
    demo: true,
    satire: [
      {
        voiceId: "chip-absolute",
        voiceName: "Chip Absolute",
        line: "Opening drive, Mahomes on his legs, and the building remembered why Monday nights still argue.",
      },
    ],
  },
  {
    id: "demo-den-kc-swift-cruise",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Celebrity look-in — Swift + Cruise at Arrowhead",
    body: "NFL posts Swift + Cruise in house for MNF (~3.07M imp / 16.2k likes per Research crawl). Platform spectacle — not a game fact.",
    postedAtLabel: "MNF platform",
    path: "public-live",
    demo: true,
    satire: [
      {
        voiceId: "chyron-carl",
        voiceName: "Chyron Carl",
        line: "Three million impressions of the booth selling the night before the football finished the sentence. That’s platform spectacle, not a play call.",
      },
    ],
  },
  {
    id: "demo-den-kc-nix-engram",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Nix→Engram answer TD — temporary tie",
    body: "Broncos answer TD Nix→Engram (temporary board swing). Verified ESPN/digest.",
    postedAtLabel: "early answer",
    path: "public-live",
    demo: true,
  },
  {
    id: "demo-den-kc-walker-60",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Walker 60-yard TD on 4th-and-1 — KC dagger",
    body: "Walker 60-yd rush TD on 4th-and-1 (Buck call noted in digest). Walker night: 173 rush, 2 TD (ESPN).",
    postedAtLabel: "Q4 4th-and-1",
    path: "public-live",
    demo: true,
    satire: [
      {
        voiceId: "wes-process",
        voiceName: "Wes Process",
        line: "Fourth-and-one at Arrowhead and they handed the referendum to a running back. Sixty yards later the math filed itself.",
      },
      {
        voiceId: "chip-absolute",
        voiceName: "Chip Absolute",
        line: "New running back, sixty yards on fourth-and-one, Arrowhead doing the thing. That’s not a cameo — that’s the Chiefs remembering they own Mondays.",
      },
      {
        voiceId: "postcard-pete",
        voiceName: "Postcard Pete",
        line: "One night, 173 yards, two scores. Cool tape. Still a postcard. We do not bronze Week 1 running backs.",
      },
    ],
  },
  {
    id: "demo-den-kc-gadget",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Fields lined up; Walker shovel TD",
    body: "Fields lined up next to Mahomes on Walker shovel TD (gadget / process theater). Live-blog color; Wes already owns 4th-and-1.",
    postedAtLabel: "gadget TD",
    path: "public-live",
    demo: true,
  },
  {
    id: "demo-den-kc-kelce",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Mahomes–Kelce long setup",
    body: "Mahomes–Kelce “so back” 59-yd setup moment (digest quote-bait). Chip budget held.",
    postedAtLabel: "midgame",
    path: "public-live",
    demo: true,
  },
  {
    id: "demo-den-kc-real-rb-meme",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Walker debut splash — “real RB” frame",
    body: "NFL/NFLMemes “Mahomes loving his new RB” / “real RB” meme pattern tied to Walker verified line. Pete anti-coronation already on Walker 4th-and-1 beat (#4).",
    postedAtLabel: "post-Walker",
    path: "public-live",
    demo: true,
  },
  {
    id: "demo-den-kc-waddle",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Waddle Broncos debut — 1 catch, 2 yards",
    body: "Jaylen Waddle Broncos debut: 1 catch, 2 yards (ESPN).",
    postedAtLabel: "box score",
    path: "public-live",
    demo: true,
    satire: [
      {
        voiceId: "postcard-pete",
        voiceName: "Postcard Pete",
        line: "Debut night, one catch, two yards. The splash narrative brought a suitcase; the box score brought a postcard.",
      },
    ],
  },
  {
    id: "demo-den-kc-peyton-audio",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Booth bits — Peyton reaction / audio out",
    body: "Awful Announcing: Peyton “No!” on Nix INT; ESPN/ABC audio out end Q1 (digest). Carl celebrity card already used.",
    postedAtLabel: "booth meta",
    path: "public-live",
    demo: true,
  },
  {
    id: "demo-den-kc-final",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "FINAL — Chiefs 31, Broncos 10",
    body: "KC 31–DEN 10. Walker 173/2 TD; Mahomes 184 pass, 2 TD pass + rush TD; Broncos 176 total yards. ESPN gameId 401872931.",
    postedAtLabel: "FINAL",
    path: "public-live",
    demo: true,
  },
  {
    id: "demo-den-kc-attendance",
    gameId: DEMO_GAME_ID,
    kind: "fact",
    authorId: null,
    headline: "Arrowhead MNF — att. 73,543",
    body: "Venue Arrowhead · ESPN/ABC · attendance 73,543 (digest).",
    postedAtLabel: "context",
    path: "public-live",
    demo: true,
  },
];
